#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     Upper,          sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     CariageMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.



void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


task main()
{
  initializeRobot();

  while(SensorValue[S2] > 40 || SensorValue[S2] < 20)
  {
  	wait1Msec(10);
  }
  PlayImmediateTone(2000, 100);
	while(SensorValue[S2] < 40 && SensorValue[S2] > 20)
  {
  	PlayImmediateTone(1000, 15);
  	wait1Msec(250);
  }
  wait1Msec(2000);

  motor[CariageMotor] = 100; //Since this is the Space Elevator Competition, it makes sense that we would start by going up.
  while(SensorValue[S2] > 25 && SensorValue[S2] != -1)
  {
  	wait1Msec(10);
	}
	motor[CariageMotor] = 75; //Since we don't want to start sliding down after we cut power, we want to decrease power slowly.
	wait1Msec(150);
	motor[CariageMotor] = 50;
	wait1Msec(100);
	motor[CariageMotor] = 25;
	wait1Msec(50);
	motor[CariageMotor] = 0;

  motor[CariageMotor] = -25; //Now we go back down.
	wait1Msec(750);
	motor[CariageMotor] = -10; //Since we don't want to start sliding down after we cut power, we want to decrease power slowly.
	wait1Msec(150);
	motor[CariageMotor] = 10;
	wait1Msec(100);
	motor[CariageMotor] = 25;
	wait1Msec(50);
	motor[CariageMotor] = 0;

	///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////


}
