#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irsensor,       sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorArm,      tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorRight,    tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNone, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoWristRight,      tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoRight,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servoLeft,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servoWristLeft,       tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int deadZone = 5;

void OpenHand()
{
    servo[servoLeft] = 200;
    servo[servoRight] = 50;
}

void CloseHand()
{
    servo[servoLeft] = 100;
    servo[servoRight] = 160;
}

void MoveArm(int power)
{
    motor[motorArm] = power;
}

task main ()
{
    waitForStart(); // wait until FCS lets us go

    while(true) // infinite loop
    {
        //writeDebugStreamLine("%d", (joystick.joy1_y1 >> 4));
        getJoystickSettings(joystick);

        // slow mode
        if(joy1Btn(7) == 1) // if the lower left trigger is pressed on controller 1 ...
        {
            if(abs(joystick.joy1_y1) > deadZone) // and the left joystick value on controller 1 isn't in the deadzone ...
            {
                motor[motorLeft]  = ((joystick.joy1_y1) / 4); // set the left motor power to the left joystick value on controller 1 divided by 3
                writeDebugStreamLine("left %d", nMotorEncoder[motorLeft]);
            }
            else
            {
                motor[motorLeft] = 0; // if the left joystick value is in the deadzone set the left motor power to 0
            }

            if(abs(joystick.joy1_y2) > deadZone) // and the right joystick value on controller 1 isn't in the deadzone ...
            {
                motor[motorRight] = ((joystick.joy1_y2) / 4); // set the right motor power to the right joystick value on controller 1 divided by 3
                //writeDebugStreamLine("right %d", nMotorEncoder[motorRight]);
            }
            else
            {
                motor[motorRight] = 0; // if the left joystick value is in the deadzone set the right motor power to 0
            }
        }
        else // regular mode
        {
            if(abs(joystick.joy1_y1) > deadZone) // if the left joystick value isn't in the deadzone ...
	        {
	            motor[motorLeft]  = joystick.joy1_y1; // set the left motor power to the left joystick value on controller 1
	        }
	        else
	        {
	            motor[motorLeft] = 0; // if the left joystick value is in the deadzone set the left motor power to 0
	        }

	        if(abs(joystick.joy1_y2) > deadZone) // if the right joystick value isn't in the deadzone ...
	        {
	            motor[motorRight] = joystick.joy1_y2; // set the right motor power to the right joystick value on controller 1
	        }
	        else
	        {
	            motor[motorRight] = 0; // if the left joystick value is in the deadzone set the right motor power to 0
	        }
        }

        if(joy2Btn(1) == 1) // if button 1 on controller 2 is pressed
        {
            OpenHand();
        }
        else if(joy2Btn(3) == 1) // if button 3 on controller 2 is pressed
        {
            CloseHand();
        }

        servo[servoWristLeft] = joystick.joy2_y2 + 128;
        servo[servoWristRight] = 127 - joystick.joy2_y2;

        if(joystick.joy2_TopHat == 0) // if up on the dpad on controller 2 is pressed
        {
            MoveArm(100);
        }
        else if(joystick.joy2_TopHat == 4) // if down on the dpad on controller 2 is pressed
        {
            MoveArm(-100);
        }
    }
}
