#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irsensor,       sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorRight,    tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorArm,      tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servoLeft,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoRight,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int deadZone = 15;

void OpenHand()
{
    servo[servoLeft] = 200;
    servo[servoRight] = 50;
}

void CloseHand()
{
    servo[servoLeft] = 100;
    servo[servoRight] = 160;
}

void MoveArm(int power)
{
    motor[motorArm] = power;
}

task main ()
{
    waitForStart(); // wait until FCS lets us go

    while(true) // infinite loop
    {
        getJoystickSettings(joystick);

        if(abs(joystick.joy1_y1) > deadZone) // if the left joystick value isn't in the deadzone ...
        {
            motor[motorLeft]  = joystick.joy1_y1; // set the left motor power to the left joystick value on controller 1
        }
        else
        {
            motor[motorLeft] = 0; // if the left joystick value is in the deadzone set the left motor power to 0
        }

        if(abs(joystick.joy1_y2) > deadZone) // if the right joystick value isn't in the deadzone ...
        {
            motor[motorRight] = joystick.joy1_y2; // set the right motor power to the right joystick value on controller 1
        }
        else
        {
            motor[motorRight] = 0; // if the left joystick value is in the deadzone set the right motor power to 0
        }

        if(joy2Btn(1) == 1) // if button 1 on controller 2 is pressed
        {
            OpenHand();
        }
        else if(joy2Btn(3) == 1) // if button 3 on controller 2 is pressed
        {
            CloseHand();
        }

        if(joystick.joy2_TopHat == 0) // if up on the dpad on controller 2 is pressed
        {
            MoveArm(100);
        }
        else if(joystick.joy2_TopHat == 4) // if down on the dpad on controller 2 is pressed
        {
            MoveArm(-100);
        }
    }
}
