#pragma config(Motor,  motorA,          left,          tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
//#pragma debuggerWindows("joystickSimple");

#include "JoystickDriver.c"
#include "drive_tank.c"

task main()
{
	StartTask(Drive);

	while(true)
	{
		// Loop is empty because we need to loop so the other task keeps running
	}
}
