#pragma config(Motor,  motorA,          single,        tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
//#pragma debuggerWindows("joystickSimple");

#include "JoystickDriver.c"
#include "controllers.c"

task main()
{
	StartTask(MotorController);

	while(true)
	{
		// Loop is empty because we need to loop so the other task keeps running
	}
}
