#pragma config(Sensor, S4,     IRseeker,       sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		string context = " IR Value:  ";
		int irVal = SensorValue[IRseeker];
		nxtDisplayString(3, "%s", context);
		nxtDisplayTextLine(4, "%d", irVal);
		wait1Msec(50);
	}



}
