#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftM,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightM,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backLeftM,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backRightM,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    frontLeftS,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    frontRightS,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    backLeftS,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    backRightS,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../auto_swive.c";

task main()
{
	RegisterMotors(frontLeftM, backLeftM, frontRightM, backRightM);
	RegisterServos(frontLeftS, backLeftS, frontRightS, backRightS);
	initializeDriveAssemblies();
nMotorEncoder[frontLeftM] =0;
SimpleDriveDirection(0, 100, 100);


}
