#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorFan1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorFan2,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoFR,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoFL,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servoBR,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servoBL,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servoGrabber,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servoTube1,           tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    servoTube2,           tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo3,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo4,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo5,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Library/controllers/tank_controller.c"
#include "Include
	bool grabbed = falss/manipulators.c"
task main()
{
	RegisterMotors(
		motorFR,
		motorFL,
		motorBL,
		motorBR
	);
	StartTask(DriveTank);
	bool grabberReady = true;
	while(true)
	{
		getJoystickSettings('joystick');
		//   !!!   begin goal grabber   !!!   //
		if ((joystick.joy1_Buttons == 1) & grabberReady == true)
		{
			grabberReady = false;
			if (grabbed == false)
			{
				grabbed = true;
				EnableGoalGrabber(true);
			}
			else
			{
				grabbed = false;
				EnableGoalGrabber(false);
			}
		}
		else if (joystick.joy1_Buttons != 1)
		{
			grabberReady = true;
		}
		///   !!!   end goal grabber   !!!   ///



		///   !!!   begin sweeper   !!!   ///disabled for now
		if (joystick.joy1_Buttons == 1)
		{
			//motor[sweeperMotor] = 128;
		}
		else
		{
			//motor[sweeperMotor] = 0;
		}
		///   !!!   end sweeper   !!!   ///
	}
}
