#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorFan1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorFan2,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     motorSweep,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoFL,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    servoFR,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_3,    servoBL,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_4,    servoBR,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_5,    servoGrabber,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servoHopper,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C3_1,    servoSweep,           tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    servoTube,            tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_5,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_6,    servo4,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "includes/writing.c"
#include "JoystickDriver.c"
#include "../library/drive_modes/simple_swerve_4m.c"
#include "includes/manipulators.c"
task main()
{
	RegisterMotors(
	motorFL,
	motorFR,
	motorBL,
	motorBR,
	motorSweep,
	motorFan1,
	motorFan2
	);
	RegisterServos(
	servoFL,
	servoFR,
	servoBL,
	servoBR,
	servoGrabber,
	servoSweep,
	servoTube
	);

	float Kp = 0.008;
	float Ki = 0.015;
	float Kd = 0.000;
	float errorPrevSum = 0;
	float errorPrev = 0;
	float error;
	float ang = 0.0;
	float newAng = 0.0;
	float n = 0.0;
	float angPrev = 0.0;
	float newAngPrev = 0.0;
	float servoSpeed = 0.0;

	//

	float errorPrevSum2 = 0;
	float errorPrev2 = 0;
	float error2;
	float ang2 = 0.0;
	float newAng2 = 0.0;
	float n2 = 0.0;
	float angPrev2 = 0.0;
	float newAngPrev2 = 0.0;
	float servoSpeed2 = 0.0;

	//

	float errorPrevSum3 = 0;
	float errorPrev3 = 0;
	float error3;
	float ang3 = 0.0;
	float newAng3 = 0.0;
	float n3 = 0.0;
	float angPrev3 = 0.0;
	float newAngPrev3 = 0.0;
	float servoSpeed3 = 0.0;

	//

	float errorPrevSum4 = 0;
	float errorPrev4 = 0;
	float error4;
	float ang4 = 0.0;
	float newAng4 = 0.0;
	float n4 = 0.0;
	float angPrev4 = 0.0;
	float newAngPrev4 = 0.0;
	float servoSpeed4 = 0.0;

	waitForStart();
	StartTask(manipulators);
	while(true)
	{
		if (abs(joystick.joy1_x1) > 35)
		{
			int powe = joystick.joy1_x1;
			motor[FRONT_LEFT_MOTOR] = powe;
			motor[FRONT_RIGHT_MOTOR] = -1 * powe;
			motor[BACK_LEFT_MOTOR] = powe;
			motor[BACK_RIGHT_MOTOR] = -1 * powe;

		}
		else if ( sqrt( pow(joystick.joy1_x2, 2) + pow( joystick.joy1_y2, 2) ) > 35)
		{
			int powe = sqrt( pow(joystick.joy1_x2, 2) + pow( joystick.joy1_y2, 2) );
			motor[FRONT_LEFT_MOTOR] = powe;
			motor[FRONT_RIGHT_MOTOR] = -1 * powe;
			motor[BACK_LEFT_MOTOR] =  powe;
			motor[BACK_RIGHT_MOTOR] = -1 *powe;
		}
		else
		{
			motor[FRONT_LEFT_MOTOR] = 0;
			motor[FRONT_RIGHT_MOTOR] = 0;
			motor[BACK_LEFT_MOTOR] = 0;
			motor[BACK_RIGHT_MOTOR] = 0;
		}

		angPrev = ang;
		newAngPrev = newAng;
		if (abs(joystick.joy1_x1) > 20)
		{
			newAng = -45.0 + n;
		}
		else if ( sqrt( pow(joystick.joy1_x2, 2) + pow( joystick.joy1_y2, 2) ) > 20)
		{
			ang = 57.5 * atan2(joystick.joy1_y2, joystick.joy1_x2);

			if (abs(ang) > 90)
			{
				if (sgn(ang * angPrev) == -1)
				{
					n = n + -1 * sgn(ang);
				}
			}
			if (n > 3)
			{
				n = 4.0;
			}
			else if (n < -3)
			{
				n = -3.0;
			}
			newAng = ang + n * 360 - 90;
		}
		error = newAng - GetCRServoPosition(FRONT_LEFT_MOTOR);
		servoSpeed = ( Kp * error ) + ( Ki * errorPrevSum ) + ( Kd * (error - errorPrev) );

		servo[FRONT_LEFT_SERVO] = 127 * ( -1 * servoSpeed + 1);

		errorPrev = error;
		errorPrevSum = errorPrevSum + errorPrev * 0.005;

		//

		angPrev2 = ang2;
		newAngPrev2 = newAng2;
		if (abs(joystick.joy1_x1) > 20)
		{
			newAng2 = 225.0 + n2;
		}
		else if ( sqrt( pow(joystick.joy1_x2, 2) + pow( joystick.joy1_y2, 2) ) > 20)
		{
			ang2 = 57.5 * atan2(joystick.joy1_y2, joystick.joy1_x2);

			if (abs(ang2) > 90)
			{
				if (sgn(ang2 * angPrev2) == -1)
				{
					n2 = n2 + -1 * sgn(ang2);
				}
			}
			if (n2 > 3)
			{
				n2 = 4.0;
			}
			else if (n2 < -3)
			{
				n2 = -3.0;
			}
			newAng2 = ang2 + n2 * 360 - 90;
		}
		error2 = newAng2 - GetCRServoPosition(FRONT_RIGHT_MOTOR);
		servoSpeed2 = ( Kp * error2 ) + ( Ki * errorPrevSum2 ) + ( Kd * (error2 - errorPrev2) );

		servo[FRONT_RIGHT_SERVO] = 127 * (servoSpeed2 + 1);

		errorPrev2 = error2;
		errorPrevSum2 = errorPrevSum2 + errorPrev2 * 0.005;

		//

		angPrev3 = ang3;
		newAngPrev3 = newAng3;
		if (abs(joystick.joy1_x1) > 20)
		{
			newAng3 = -135.0 + n3 + 180;
		}
		else if ( sqrt( pow(joystick.joy1_x2, 2) + pow( joystick.joy1_y2, 2) ) > 20)
		{
			ang3 = 57.5 * atan2(joystick.joy1_y2, joystick.joy1_x2);

			if (abs(ang3) > 90)
			{
				if (sgn(ang3 * angPrev3) == -1)
				{
					n3 = n3 + -1 * sgn(ang3);
				}
			}
			if (n3 > 3)
			{
				n3 = 4.0;
			}
			else if (n3 < -3)
			{
				n3 = -3.0;
			}
			newAng3 = ang3 + n3 * 360 - 90;
		}
		error3 = newAng3 - GetCRServoPosition(BACK_LEFT_MOTOR);
		servoSpeed3 = ( Kp * error3 ) + ( Ki * errorPrevSum3 ) + ( Kd * (error3 - errorPrev3) );

		servo[BACK_LEFT_SERVO] = 127 * (-1 * servoSpeed3 + 1);

		errorPrev3 = error3;
		errorPrevSum3 = errorPrevSum3 + errorPrev3 * 0.005;

		//

		angPrev4 = ang4;
		newAngPrev4 = newAng4;
		if (abs(joystick.joy1_x1) > 20)
		{
			newAng4 = -45.0 + n4 + 180;
		}
		else if ( sqrt( pow(joystick.joy1_x2, 2) + pow( joystick.joy1_y2, 2) ) > 20)
		{
			ang4 = 57.5 * atan2(joystick.joy1_y2, joystick.joy1_x2);

			if (abs(ang4) > 90)
			{
				if (sgn(ang4 * angPrev4) == -1)
				{
					n4 = n4 + -1 * sgn(ang4);
				}
			}
			if (n4 > 3)
			{
				n4 = 4.0;
			}
			else if (n4 < -3)
			{
				n4 = -3.0;
			}
			newAng4 = ang4 + n4 * 360 - 90;
		}
		error4 = newAng4 - GetCRServoPosition(BACK_RIGHT_MOTOR);
		servoSpeed4 = ( Kp * error4 ) + ( Ki * errorPrevSum4 ) + ( Kd * (error4 - errorPrev4) );

		servo[BACK_RIGHT_SERVO] = 127 * (servoSpeed4 + 1);

		errorPrev4 = error4;
		errorPrevSum4 = errorPrevSum4 + errorPrev4 * 0.005;

		wait1Msec(100);

	}
}
