#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorFan1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorFan2,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     motorSweep,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoFL,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    servoFR,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_3,    servoBL,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_4,    servoBR,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_5,    servoGrabber,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servoHopper,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C3_1,    servoSweep,           tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    servoTube,            tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_5,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_6,    servo4,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "includes/writing.c"
#include "JoystickDriver.c"
#include "../library/drive_modes/simple_swerve_4m.c"

task main()
{
	RegisterMotors(
	motorFL,
	motorFR,
	motorBL,
	motorBR,
	motorSweep,
	motorFan1,
	motorFan2
	);
	RegisterServos(
	servoFL,
	servoFR,
	servoBL,
	servoBR,
	servoGrabber,
	servoSweep,
	servoTube
	);

	float Kp = 0.008;
	float Ki = 0.015;
	float Kd = 0.002;
	float errorPrevSum = 0;
	float errorPrev = 0;
	float error;
	float ang = 0.0;
	float newAng = 0.0;
	float n = 0.0;
	float angPrev = 0.0;
	float newAngPrev = 0.0;
	float servoSpeed = 0.0;

	waitForStart();
	while(true)
	{
		if ( sqrt( pow(joystick.joy1_x2, 2) + pow( joystick.joy1_y2, 2) ) > 20)
		{
			int powe = sqrt( pow(joystick.joy1_x2, 2) + pow( joystick.joy1_y2, 2) );
			motor[FRONT_LEFT_MOTOR] = powe;
			motor[FRONT_RIGHT_MOTOR] = -1 * powe;
			motor[BACK_LEFT_MOTOR] = powe;
			motor[BACK_RIGHT_MOTOR] = -1 * powe;
		}
		else
		{
			motor[FRONT_LEFT_MOTOR] = 0;
			motor[FRONT_RIGHT_MOTOR] = 0;
			motor[BACK_LEFT_MOTOR] = 0;
			motor[BACK_RIGHT_MOTOR] = 0;
		}

		angPrev = ang;
		newAngPrev = newAng;
		if ( sqrt( pow(joystick.joy1_x2, 2) + pow( joystick.joy1_y2, 2) ) > 20)
		{
			ang = 57.5 * atan2(joystick.joy1_y2, joystick.joy1_x2);

			if (abs(ang) > 90)
			{
				if (sgn(ang * angPrev) == -1)
				{
					n = n + -1 * sgn(ang);
				}
			}
			newAng = ang + n * 360 - 90;
		}
		error = newAng - GetCRServoPosition(BACK_RIGHT_MOTOR);
		nxtDisplayTextLine(3, "%f", ang);
		nxtDisplayTextLine(4, "%f", newAng);
		nxtDisplayTextLine(5, "%f", error);
		nxtDisplayTextLine(6, "%f", n);
		servoSpeed = ( Kp * error ) + ( Ki * errorPrevSum ) + ( Kd * (error - errorPrev) );

		servo[BACK_RIGHT_SERVO] = 127 * ( -1 * servoSpeed + 1);
		servo[BACK_LEFT_SERVO] = 127 * ( -1 * servoSpeed + 1);
		servo[FRONT_RIGHT_SERVO] = 127 * ( -1 * servoSpeed + 1);
		servo[FRONT_LEFT_SERVO] = 127 * ( -1 * servoSpeed + 1);

		errorPrev = error;
		errorPrevSum = errorPrevSum + errorPrev * 0.005;
		wait1Msec(100);

	}
}
