#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     sensorIR,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFR,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorArm,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoFR,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servoBR,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servoBL,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servoFL,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servoWrist,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servoRoller,          tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";

float slowMult = 1; // slow mode multiplier
float slowMultArm = 1; //slow mode multiplier for arm
int deadZone = 15;
float degToServo = (255.0/190.0); // converts degrees into servo values
int pos; // angle in degrees based on right joystick
float dist; // motor power based on right joystick
int servoPos; // servo values based on pos

long wayTooLong = 1000;  // millisecond threshold for absolute stall
long tooLong = 250;  // millisecond threshod for partial stall
long sigMove = 100; // How many encoder ticks is a 'significant' movement

//variables used for stall code need to be initialized
int lastDirection[] = {0, 0, 0}; // Direction of last power -1 (reverse), 0 (stopped) or 1 (forward)
long timeLastSigMove[] = {0, 0, 0}; // Time last significant move occurred
long encLastSigMove[] = {0, 0, 0}; // Encoder reading at last significant move

int StallCode(tMotor motorSentTo, int wantedPower)
{
	int motorIndex;  //index value for the arrays we are storing values in.
	int direction = 0;
	switch(motorSentTo) //which motor power is being sent to
	{
		case motorFR: // This is the name of one of the motors as referenced in the configuraiton.
			motorIndex = 0;
			break;
		case motorArm:
			motorIndex = 1;
			break;
		default:
			break;
	}

	if (abs(wantedPower) < deadZone)  // Power below threshold, mark as stopped.
		direction = 0;
  else
  	direction = (wantedPower < 0) ? -1 : 1;

	if (direction == 0 || lastDirection[motorIndex] != direction)  // Stopped or changed direction.	Allow whatever power desired this time.
		{
    	lastDirection[motorIndex] = direction;
			timeLastSigMove[motorIndex]	 = time1[T1];
			encLastSigMove[motorIndex] = nMotorEncoder[motorSentTo];

			return wantedPower;
		}

 	lastDirection[motorIndex] = direction;

	if ( abs(encLastSigMove[motorIndex] - nMotorEncoder[motorSentTo]) > sigMove)  // Moved far enough to be considered significant, mark
		{
			timeLastSigMove[motorIndex]	= time1[T1];
			encLastSigMove[motorIndex] = nMotorEncoder[motorSentTo];

			return wantedPower;
		}

	if ( (time1[T1] - timeLastSigMove[motorIndex]) > wayTooLong )  // Time since last significant move too long, stalled
		{
			PlayTone(650,4);
			return 0;
		}

	if ( (time1[T1] - timeLastSigMove[motorIndex]) > tooLong )  // Time since last significant move too long, stalled
		{
			PlayTone(365,4);
			return wantedPower / 2;
		}

	return wantedPower;	// Haven’t moved far enough yet to be significant but haven’t timed out yet
}

task main()
{
	// set servos to default position
	servo[servoFL] = 90 * degToServo;
	servo[servoFR] = 90 * degToServo;
	servo[servoBL] = 90 * degToServo;
	servo[servoBR] = 90 * degToServo;

	while (true) // infinite loop
	{
		waitForStart();
		ClearTimer(T1);
		nMotorEncoder[motorFR] = 0;
		nMotorEncoder[motorArm] = 0;
		getJoystickSettings(joystick); // find joystick values

		pos = (int)radiansToDegrees(atan2(joystick.joy1_y2, joystick.joy1_x2)); // get servo degrees based on right joystick x and y values
		/*if(joystick.joy1_x2 == 0)
		{
			pos = 0;
		}*/
		dist = sqrt(joystick.joy1_y2 * joystick.joy1_y2 + joystick.joy1_x2 * joystick.joy1_x2); // use distance formula to get motor powers based on right joystick x and y values

		// slow mode
		if (joy1Btn(6)) // right bumper
		{
			slowMult = 0.3; // do slow mode
		}
		else
		{
			slowMult = 1; // don't do slow mode
		}

		int motorPower = (int)(dist * slowMult); // motor power values with slow mode multiplier

		if (abs(joystick.joy1_x1) > deadZone) // turning based on left joystick
		{
			// motor power based on joystick
			motor[motorFL] = joystick.joy1_x1 * slowMult;
			motor[motorFR] = StallCode(motorFR, -1 * joystick.joy1_x1 * slowMult);
			motor[motorBL] = joystick.joy1_x1 * slowMult;
			motor[motorBR] = -1 * joystick.joy1_x1 * slowMult;

			// set servo positions for rotation
			servo[servoFL] = 45 * degToServo;
			servo[servoFR] = 135 * degToServo;
			servo[servoBL] = 135 * degToServo;
			servo[servoBR] = 45 * degToServo;
		}
		else if (dist < deadZone) // don't move
		{
			motor[motorFL] = 0;
			motor[motorFR] = StallCode(motorFR, 0);
			motor[motorBL] = 0;
			motor[motorBR] = 0;
		}
		else if (joystick.joy1_y2 > 0 && joystick.joy1_x2 > 0) // quadrant 1
		{
			motor[motorFL] = motorPower;
			motor[motorFR] = StallCode(motorFR, motorPower);
			motor[motorBL] = motorPower;
			motor[motorBR] = motorPower;

			servoPos = (int)((pos) * degToServo);

			servo[servoFL] = servoPos;
			servo[servoFR] = servoPos;
			servo[servoBL] = servoPos;
			servo[servoBR] = servoPos;
		}
		else if (joystick.joy1_y2 > 0 && joystick.joy1_x2 < 0) // quadrant 2
		{
			motor[motorFL] = motorPower;
			motor[motorFR] = StallCode(motorFR, motorPower);
			motor[motorBL] = motorPower;
			motor[motorBR] = motorPower;

			servoPos = (int)((pos) * degToServo);

			servo[servoFL] = servoPos;
			servo[servoFR] = servoPos;
			servo[servoBL] = servoPos;
			servo[servoBR] = servoPos;
		}
		else if (joystick.joy1_y2 < 0 && joystick.joy1_x2 < 0) // quadrant 3
		{
			motor[motorFL] = motorPower * -1;
			motor[motorFR] = StallCode(motorFR, motorPower * -1);
			motor[motorBL] = motorPower * -1;
			motor[motorBR] = motorPower * -1;

			pos = pos - 180; // change degrees to numbers between 0 and 180 because we're not using CR servos
			servoPos = (int)((pos) * degToServo);

			servo[servoFL] = servoPos;
			servo[servoFR] = servoPos;
			servo[servoBL] = servoPos;
			servo[servoBR] = servoPos;
		}
		else if (joystick.joy1_y2 < 0 && joystick.joy1_x2 > 0) // quadrant 4
		{
			motor[motorFL] = motorPower * -1;
			motor[motorFR] = StallCode(motorFR, motorPower * -1);
			motor[motorBL] = motorPower * -1;
			motor[motorBR] = motorPower * -1;

			pos = pos - 180; // change degrees to numbers between 0 and 180 because we're not using CR servos
			servoPos = (int)((pos) * degToServo);

			servo[servoFL] = servoPos;
			servo[servoFR] = servoPos;
			servo[servoBL] = servoPos;
			servo[servoBR] = servoPos;
		}

		if(abs(joystick.joy2_y1) > deadZone)
		{
			if (joy2Btn(6)) // right bumper
			{
				slowMultArm = 0.3; // do slow mode
			}
			else
			{
				slowMultArm = 1; // don't do slow mode
			}

			motor[motorArm]= StallCode(motorArm, joystick.joy2_y1 * slowMultArm);
		}
		else
		{
			motor[motorArm]= StallCode(motorArm, 0);
		}

		servo[servoWrist] = joystick.joy2_y2 + 128; // wrist servo positions based on right joystick

		if(joy2Btn(5)) // left bumper
		{
			servo[servoRoller] = 255; // spin roller in
		}
		else
		{
			servo[servoRoller] = 128; // don't spin roller
		}

		if(joy2Btn(1))
		{
			motor[motorFlag] = 100;
		}
		else if(joy2Btn(3))
		{
			motor[motorFlag] = -100;
		}
		else
		{
			motor[motorFlag] = 0;
		}
	}
}
