#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     sensorIR,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorFR,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBR,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorArm,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoFR,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servoBR,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servoBL,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servoFL,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servoWrist,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servoRoller,          tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";

float degToServo = (255.0/192.0); // converts degrees into servo values

task main()
{
	waitForStart();

	nMotorEncoder[motorFL] = 0;

	while(SensorValue(sensorIR) != 4) // go forward until IR beacon
	{
		motor[motorFL] = 20;
		motor[motorFR] = 20;
		motor[motorBL] = 20;
		motor[motorBR] = 20;
	}
	// stop motors
	motor[motorFL] = 0;
	motor[motorFR] = 0;
	motor[motorBL] = 0;
	motor[motorBR] = 0;

	// place cube with arm

	while(nMotorEncoder[motorFL] < 1440) // go forward until there's space to move onto ramp
	{
		motor[motorFL] = 20;
		motor[motorFR] = 20;
		motor[motorBL] = 20;
		motor[motorBR] = 20;
	}
	// stop motors
	motor[motorFL] = 0;
	motor[motorFR] = 0;
	motor[motorBL] = 0;
	motor[motorBR] = 0;

	// turn servos 90 deg
	// go forward until there's space to get onto ramp
	// turn servos back
	// go onto ramp
}
