#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lazySuzan,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoFL,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servoFR,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servoBL,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servoBR,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    brush,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";


float slowMult = 1;
int deadZone = 10;

void ArmControlFunc()
{

	if (abs(joystick.joy2_x1) > deadZone)
	{
		motor [lazySuzan] = joystick.joy1_x1;
	}
	if (abs(joystick.joy2_y1) > deadZone)
	{
		motor [arm] = joystick.joy2_y1;
	}
	if (joy2Btn(4) == 1)//left bumper
	{
		servo [wrist] = 100;//this value will change, i don't know the servo value system well, or the orientation of the servo
		//this also goes with all the other servo values

	}
	if (joy2Btn(6) == 1)//left trigger
	{
		servo [wrist] = 200;
	}
	if (joy2Btn(7) == 1)//right trigger
	{
		//servo [brush] ++ 360;//i don't know how to use continual rotation servos
	}
}

	task armControl()
	{
		while(true)
		{
			getJoystickSettings(joystick);
			if (abs(joystick.joy2_y1) > deadZone)
			{
				ArmControlFunc();
			}
		}
	}

	task main()
	{
		while (true)
		{
			getJoystickSettings(joystick);
			StartTask(armControl);

			int pos = atan(joystick.joy1_y2 / joystick.joy1_x2);
			float dist = sqrt(joystick.joy1_y2 * joystick.joy1_y2 + joystick.joy1_x2 * joystick.joy1_x2);

			if (joystick.joy1_Buttons == 6)
			{
				slowMult = 1;
			}
			else
			{
				slowMult = 0.3;
			}

			if (dist <= deadZone)
			{
				motor[motorFL] = 0;
				motor[motorFR] = 0;
				motor[motorBL] = 0;
				motor[motorBR] = 0;
			}
			else if (dist > deadZone && pos >= 0)
			{
				motor[motorFL] = dist * 0.75;
				motor[motorFR] = dist * 0.75;
				motor[motorBL] = dist * 0.75;
				motor[motorBR] = dist * 0.75;

				float servoPos = pos * 1.416;

				servo[servoFL] = servoPos;
				servo[servoFR] = servoPos;
				servo[servoBL] = servoPos;
				servo[servoBR] = servoPos;
			}
			else
			{
				motor[motorFL] = dist * -0.75;
				motor[motorFR] = dist * -0.75;
				motor[motorBL] = dist * -0.75;
				motor[motorBR] = dist * -0.75;

				float servoPos = (pos - 180) * 1.416;

				servo[servoFL] = servoPos;
				servo[servoFR] = servoPos;
				servo[servoBL] = servoPos;
				servo[servoBR] = servoPos;
			}


		}

	}
