#pragma config(Sensor, S1,     bumper,         sensorTouch)
#pragma config(Sensor, S2,     sonarL,         sensorSONAR)
#pragma config(Sensor, S3,     sonarR,         sensorSONAR)
#pragma config(Sensor, S4,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          driveMtrL,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          driveMtrR,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TANK_2M

#include "includes.h"

task main()
{
	InitBot();

	StartTask(MapRoom);
	wait1Msec(1000);
	LeaveBase();
	DrivePerimeterRight();
	//ReturnHome();
}
