#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     sonarL,         sensorSONAR)
#pragma config(Sensor, S3,     sonarR,         sensorSONAR)
#pragma config(Sensor, S4,     gyroSensor,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     driveMtrL,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     drivemtrR,     tmotorTetrix, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TANK_2M

#include "includes.h"

task main()
{
	InitBot();

	StartTask(MapRoom);
	//ReturnHome();
}
