#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMid,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     LeftSides,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightMid,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     RightSides,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    goalGrabber,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define PARALLEL_PAIRS

#include "includes/includes.h"

task main()
{
	RegisterDriveMotorPair(LeftMid, RightMid, PairCount1);
	RegisterDriveMotorPair(LeftSides, RightSides, PairCount2);

	waitForStart();

	StartTask(DriveTank);

	while(true)
	{

		// make sure we don't exit
	}
}
