#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    servoFR,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    servoFL,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    servoBL,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    servoBR,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_5,    servoBrush1,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_6,    servoBrush2,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifndef SWIVE_DRIVE.C
#define SWIVE_DRIVE.C

#include "../Library/drive_modes/simpleswerve_4m.c"
#include "JoystickDriver.c"

task drive()
{
	while(true)
	{
		getJoystickSettings(joystick);

		initializeSwiveGeometry();

		int X_Velocity = JoystickToMetersPerSecond(joystick.joy1_x2, joystick.joy1_x1);
		int Y_Velocity = JoystickToMetersPerSecond(joystick.joy1_y2, joystick.joy1_x1);
		int Z_Velocity = JoystickToRadiansPerSecond(joystick.joy1_x1);

		float angleZ[4];
		int speedXY[4];

		for (POS p; p < BACK_RIGHT; p++)
		{
			angleZ[p] = CalculateMotorAngle(X_Velocity, Y_Velocity, Z_Velocity, p);
			speedXY[p] = CalculateMotorSpeed(X_Velocity, Y_Velocity, Z_Velocity, p);
			SetDriveVelocity(speedXY[p], angleZ[p], p);
		}

	}
}
#endif
