#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEAD_ZONE (15)
#define JOY_INCRIMENTS (128)
#define MAX_POWER (100)

#include "joystickDriver.c"

task main()
{
	while(true)
	{
		SetMotorPowerJoy(left);
		SetMotorPowerJoy(right);
	}
}

void SetMotorPowerJoy(string motorName)
{
	if (abs(joystick.joy1_y1) > DEAD_ZONE)
	{
		int convert = (MAX_POWER - DEAD_ZONE) / JOY_INCRIMENTS;
	}
	else
	{
		StopMotor(motorName);
	}
}

void StopMotor(tMotor motorName)
{
	motor[motorName] = 0;
}
