#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     seeker,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     sholder,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     flag,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    arm,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    wrist,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//zone in which the joystick does not send values to the motors.
int deadZone = 15;
//int shootingSpeed = 100;

/*long wayTooLong = 1000;  // millisecond threshold for absolute stall
long tooLong = 250;  // millisecond threshod for partial stall
long sigMove = 100; // How many encoder ticks is a 'significant' movement

//variables used for stall code need to be initialized
int lastDirection[] = {0, 0, 0}; // Direction of last power -1 (reverse), 0 (stopped) or 1 (forward)
long timeLastSigMove[] = {0, 0, 0}; // Time last significant move occurred
long encLastSigMove[] = {0, 0, 0}; // Encoder reading at last significant move

int StallCode(tMotor motorSentTo, int wantedPower)
{
	int motorIndex;  //index value for the arrays we are storing values in.
	int direction = 0;
	switch(motorSentTo) //which motor power is being sent to
	{
		case Left: // This is the name of one of the motors as referenced in the configuraiton.
			motorIndex = 0;
			break;
		case Right:
			motorIndex = 1;
			break;
		/*case flag:
			motorIndex = 2;
			break;*/
		/*default:
			break;
	}

	if (abs(wantedPower) < deadZone)  // Power below threshold, mark as stopped.
		direction = 0;
  else
  	direction = (wantedPower < 0) ? -1 : 1;

	if (direction == 0 || lastDirection[motorIndex] != direction)  // Stopped or changed direction.	Allow whatever power desired this time.
		{
    	lastDirection[motorIndex] = direction;
			timeLastSigMove[motorIndex]	 = time1[T1];
			encLastSigMove[motorIndex] = nMotorEncoder[motorSentTo];

			return wantedPower;
		}

 	lastDirection[motorIndex] = direction;

	if ( abs(encLastSigMove[motorIndex] - nMotorEncoder[motorSentTo]) > sigMove)  // Moved far enough to be considered significant, mark
		{
			timeLastSigMove[motorIndex]	= time1[T1];
			encLastSigMove[motorIndex] = nMotorEncoder[motorSentTo];

			return wantedPower;
		}

	if ( (time1[T1] - timeLastSigMove[motorIndex]) > wayTooLong )  // Time since last significant move too long, stalled
		{
			PlayTone(650,4);
			return 0;
		}

	if ( (time1[T1] - timeLastSigMove[motorIndex]) > tooLong )  // Time since last significant move too long, stalled
		{
			PlayTone(365,4);
			return wantedPower / 2;
		}

	return wantedPower;	// Haven’t moved far enough yet to be significant but haven’t timed out yet
}*/

//This is the slow mode function that allows you to use the slow mode. Slow mode is the mode that allows you to slow down the robot.
void slowMode()
{
	//if the absolute value of joystick.joy1_y1 is greater than varible deadZone.
	if (abs(joystick.joy1_y1) > deadZone)
	{
		//The left motor's value is equal to the value of joystick.joy1_y1 divided by 4.
		motor[Left] = joystick.joy1_y1 / 4;
	}
	//if the if statement above is not entered then
	else
	{
		//The left motor's value equals 0.
		motor[Left] = 0;
	}
	//if the absolute value of joystick.joy1_y2 is greater than varible deadZone
	if (abs(joystick.joy1_y2) > deadZone)
	{
		//The right motor's value is equal to the value of joystick.joy_y2 divided by 4
		motor[Right] = joystick.joy1_y2 / 4;
	}
	else
	{
		//The right motor's value equals 0
		motor[Right] = 0;
	}
}

//This is th second task that splits the two joysticks into two tasks to help with efficency
task Joystick2()
{
	while (true)
	{
		getJoystickSettings(joystick);

		if (joy2Btn(3) == 1)
		{
			motor[flag] = 100;
		}
		else if (joy2Btn(2) == 1)
		{
			motor[flag] = -100;
		}
		else
		{
			motor[flag] = 0;
		}

		if (joystick.joy2_y1 > deadZone)
		{
			motor[sholder] = 40;
		}
		else if (joystick.joy2_y1 < -deadZone)
		{
			motor[sholder] = -40;
		}
		else
		{
			motor[sholder] = 0;
		}

			if (abs(joystick.joy2_y2) > deadZone)
			{
				servo[wrist] = joystick.joy2_y2 + 128;
			}
			else
			{
				servo[wrist] = 128;
			}


		if (joystick.joy2_TopHat == 4)
		{
			servo[arm] = 224;
		}
		else if(joystick.joy2_TopHat == 0)
		{
			servo[arm] = 40;
		}
	}
}

task main()
{
	waitForStart();
	StartTask(Joystick2);
	while (true)
	{

		getJoystickSettings(joystick);
		if (joy1Btn(8) == 1)
		{
			slowMode();
		}
		else
		{
			if (abs(joystick.joy1_y1) > deadZone)
			{
				motor[Left] = joystick.joy1_y1;
			}
			else
			{
				motor[Left] = 0;
			}

			if (abs(joystick.joy1_y2) > deadZone)
			{
				motor[Right] = joystick.joy1_y2;
			}
			else
			{
				motor[Right] = 0;
			}
		}
	}
}
