#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IRseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Flipper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

int DistanceToIr = 0;

task main()
{
	waitForStart();

	while (SensorValue(IRseeker) >= 3)
	{
		motor[LeftMotor] = -40;
		motor[RightMotor] = -40;
	}

	DistanceToIr = nMotorEncoder[LeftMotor];

	motor[LeftMotor] = 0;
	motor[RightMotor] = 0;
	nMotorEncoder[LeftMotor] = 0;

	while (nMotorEncoder[LeftMotor] < 950)
	{
		motor[LeftMotor] = 50;
		motor[RightMotor] = -50;
	}
	motor[LeftMotor] = 0;
	motor[RightMotor] = 0;
	nMotorEncoder[LeftMotor] = 0;

	servo[Flipper] = 50;

	wait1Msec(500);

	while (nMotorEncoder[LeftMotor] > -650)
	{
		motor[LeftMotor] = -50;
		motor[RightMotor] = 50;
	}

	servo[Flipper] = 0;

	motor[LeftMotor] = 0;
	motor[RightMotor] = 0;
	nMotorEncoder[LeftMotor] = 0;

	DistanceToIr = DistanceToIr - 500;
	DistanceToIr = DistanceToIr * -1;

	while (nMotorEncoder[LeftMotor] > DistanceToIr)
	{
		motor[LeftMotor] = 50;
		motor[RightMotor] = 50;
	}

	while (nMotorEncoder[LeftMotor] > -650)
	{
		motor[LeftMotor] = -50;
		motor[RightMotor] = 50;
	}

	motor[LeftMotor] = 0;
	motor[RightMotor] = 0;
	nMotorEncoder[LeftMotor] = 0;

	while (nMotorEncoder[LeftMotor] < 2880)
	{
		motor[LeftMotor] = 50;
		motor[RightMotor] = 50;
	}

	motor[LeftMotor] = 0;
	motor[RightMotor] = 0;
	nMotorEncoder[LeftMotor] = 0;

	while (nMotorEncoder[LeftMotor] > -650)
	{
		motor[LeftMotor] = -50;
		motor[RightMotor] = 50;
	}

	motor[LeftMotor] = 0;
	motor[RightMotor] = 0;
	nMotorEncoder[LeftMotor] = 0;

	while (nMotorEncoder[LeftMotor] < 2880)
	{
		motor[LeftMotor] = 50;
		motor[RightMotor] = 50;
	}

	motor[LeftMotor] = 0;
	motor[RightMotor] = 0;
	nMotorEncoder[LeftMotor] = 0;

}
