#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Encoder,       tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    Winch,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


/////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////Instructions//////////////////////////////////////////
//   1)input value that you want servo to increase by on line 29											 //
//   2)wait for servo to initialize																										 //
//   3)after servo has initialized, press right arrow																	 //
//   4)after reading debug stream, press the right arrow to continue									 //
//   5)watch servo spin																																 //
//   6)press right arrow to read encoder value																				 //
//   7)press right arrow to finish																										 //
/////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////
/////////Input Value Here/////////////
/**/	int servoPosition = 0;		  /**/
//////////////////////////////////////
//////////////////////////////////////

int servoZero = 11;

	servo[Winch] = servoZero;		//initializes servo

		while(nNxtButtonPressed == -1)
	{
	}

	writeDebugStreamLine(" before encoder value is %d", nMotorEncoder(Encoder));

	while(nNxtButtonPressed == -1)
	{
	}

	wait1Msec(1000);

	servo[Winch] = 11 + servoPosition;

	wait1Msec(1000);
	while(nNxtButtonPressed == -1)
	{
	}

		writeDebugStreamLine(" after encoder value is %d", nMotorEncoder(Encoder));

		wait1Msec(1000);

	while(nNxtButtonPressed == -1)
	{
	}

}







//<10 is infinite left. > 110.25? is infinite right.
