#pragma config(Sensor, S2,     ir,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "../library/sensors/ir_seeker.c"

#pragma debuggerWindows("joystickSimple");
#pragma debuggerWindows("nxtLCDScreen");
#pragma debuggerWindows("nxtDevices");

int ir_mode;
int ir_raw;
int ir_type;
int ir_value;

task main()
{
	RegisterIRSeeker(ir);


	while(true)
	{
		getJoystickSettings(joystick);
		ir_mode=SensorMode[ir];
		ir_raw=SensorRaw[ir];
		ir_type=SensorType[ir];
		ir_value=SensorValue[ir];

		wait1Msec(500);

	}
}
