#pragma config(Sensor, S1,     colorL,         sensorCOLORFULL)
#pragma config(Sensor, S2,     colorR,         sensorCOLORFULL)
#pragma config(Motor,  motorA,          mtrL,          tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,          mtrR,          tmotorNXT, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
#pragma debuggerWindows("joystickSimple");

//Controller.c is included, because we need to have the deazone declared for motors.c
#include "controller.c"
#include "motors.c"

//Un-comment whatever drive you want to use and comment out the other ones
#include "lineFollower1.c"
//#include "lineFollower2.c"

task main()
{
	StartTask(Line);
	StartTask(Controller);
	while(true)
	{
		//This is empty to keep the program running
	}
}
