#pragma config(Motor,  motorA,          mtrL,          tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          mtrR,          tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
//#pragma debuggerWindows("joystickSimple");

#include "motorsRight.c"
#include "motorsLeft.c"
#include "controller.c"
#include "tank.c"
//#include "arcade.c"
//Un-comment whatever drive you want to use and comment out the other one (either tank.c or arcade.c).

task main()
{
StartTask(Controller);
StartTask(Drive);

	while(true)
	{

	}
}
/*
																				/\
																			 //\\
																			///\\\
																		 ////\\\\
																		/////\\\\\
																			///\\\
																		 ////\\\\
																		/////\\\\\
																	 //////\\\\\\
																	///////\\\\\\\
																 		/////\\\\\
																	 //////\\\\\\
																	///////\\\\\\\
																 ////////\\\\\\\\
																/////////\\\\\\\\\
																	///////\\\\\\\
																 ////////\\\\\\\\
																/////////\\\\\\\\\
															 //////////\\\\\\\\\\
															///////////\\\\\\\\\\\
																			 ||||
																			 ||||
																			 ||||

*/
