#pragma config(Sensor, S1,     colorL,         sensorCOLORFULL)
#pragma config(Sensor, S2,     colorR,         sensorCOLORFULL)
#pragma config(Motor,  motorA,          mtrL,          tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,          mtrR,          tmotorNXT, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
#pragma debuggerWindows("joystickSimple");

#include "controller.c"
#include "motors.c"

//Un-comment whatever drive you want to use and comment out the other ones
//#include "tank.c"
//#include "arcade.c"

task main()
{
	//Starts tasks to get joystick values and whatever drive was chosen
	StartTask(Controller);
	StartTask(Drive);

	while(true)
	{
		//If button 1 is pressed, display the current color sensor value
		if(joy1Btn(1) == 1)
		{
			nxtDisplayTextLine(1, "Sensor Value: %d", SensorValue[colorL]);
		}
	}
}
/*
																				/\
																			 //\\
																			///\\\
																		 ////\\\\
																		/////\\\\\
																			///\\\
																		 ////\\\\
																		/////\\\\\
																	 //////\\\\\\
																	///////\\\\\\\
																 		/////\\\\\
																	 //////\\\\\\
																	///////\\\\\\\
																 ////////\\\\\\\\
																/////////\\\\\\\\\
																	///////\\\\\\\
																 ////////\\\\\\\\
																/////////\\\\\\\\\
															 //////////\\\\\\\\\\
															///////////\\\\\\\\\\\
																			 ||||
																			 ||||
																			 ||||

*/
