#pragma config(Motor,  motorA,          mtrL,          tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,          mtrR,          tmotorNXT, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
//#pragma debuggerWindows("joystickSimple");

#include "motors.c"
#include "controller.c"
#include "tank.c"
//#include "arcade.c"

//Un-comment whatever drive you want to use and comment out the other one (either tank.c or arcade.c).

task main()
{
	StartTask(Controller); //Starts task of getJoystickSettings
	StartTask(Drive); //starts task of what drive system was chosen above

	while(true)
	{
		//This is an empty loop to keep the program running
	}
}
/*
																				/\
																			 //\\
																			///\\\
																		 ////\\\\
																		/////\\\\\
																			///\\\
																		 ////\\\\
																		/////\\\\\
																	 //////\\\\\\
																	///////\\\\\\\
																 		/////\\\\\
																	 //////\\\\\\
																	///////\\\\\\\
																 ////////\\\\\\\\
																/////////\\\\\\\\\
																	///////\\\\\\\
																 ////////\\\\\\\\
																/////////\\\\\\\\\
															 //////////\\\\\\\\\\
															///////////\\\\\\\\\\\
																			 ||||
																			 ||||
																			 ||||

*/
