#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     mot1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     mot2,          tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
#pragma debuggerWindows("joystickGame");

#define TANK_2M

#include "JoystickDriver.c"
#include "../library/controllers/controller_defines.h"
#include "../library/sensors/gyro.c"
#include "../library/controllers/tank_controller.c"
#include "../library/drive/gyro_drive.c"

int TURN_TEST = 45; // will turn left 45 degrees for test

task main()
{
	ASSUME_CONTROLLER_INPUT = false;
	RegisterDriveMotors(mot1, mot2);
	RegisterGyroSensor(gyroSensor);
	StartTask(Drive);

	while(true)
	{
		if(joy1Btn(1)==1)
		{
			StopTask(Drive);
			TurnLeftDegrees(10,50);
			StartTask(Drive);
		}
		if(joy1Btn(2)==1)
		{
			StopTask(Drive);
			TurnRightDegrees(10,50);
			StartTask(Drive);
		}
		StopAllDriveMotors();
	}
}
