#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     mot1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     mot2,          tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
#pragma debuggerWindows("joystickGame");

#define TANK_2M

#include "JoystickDriver.c"
#include "../library/controllers/controller_defines.h"
#include "../library/sensors/gyro.c"
#include "../library/controllers/tank_controller.c"
#include "../library/drive/gyro_drive.c"

const int TURN_TEST_POWER = 30;

task main()
{
	ASSUME_CONTROLLER_INPUT = false;
	RegisterDriveMotors(mot1, mot2);
	RegisterGyroSensor(gyroSensor);

	while(true)
	{
		if(joy1Btn(1)==1)
		{
			TurnLeftDegrees(10,TURN_TEST_POWER);
		}
		if(joy1Btn(2)==1)
		{
			TurnRightDegrees(10,TURN_TEST_POWER);
		}
		if(joy1Btn(3)==1)
		{
			TurnLeftDegrees(90,TURN_TEST_POWER);
			StopAllDriveMotors();
			TurnRightDegrees(180,TURN_TEST_POWER);
			StopAllDriveMotors();
			TurnLeftDegrees(180,TURN_TEST_POWER);
			StopAllDriveMotors();
			TurnRightDegrees(90,TURN_TEST_POWER);
			StopAllDriveMotors();
		}
		StopAllDriveMotors();
	}

}
