
#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int deadZone = 5;

task main()
{
    waitForStart(); // wait until FCS lets us go
    while(true)
    {
        if(abs(joystick.joy1_y1) > deadZone) // if the left joystick value isn't in the deadzone ...
	        {
	            motor[motorLeft]  = joystick.joy1_y1; // set the left motor power to the left joystick value on controller 1
	        }
	        else
	        {
	            motor[motorLeft] = 0; // if the left joystick value is in the deadzone set the left motor power to 0
	        }

	        if(abs(joystick.joy1_y2) > deadZone) // if the right joystick value isn't in the deadzone ...
	        {
	            motor[motorRight] = joystick.joy1_y2; // set the right motor power to the right joystick value on controller 1
	        }
	        else
	        {
	            motor[motorRight] = 0; // if the left joystick value is in the deadzone set the right motor power to 0
	        }
    }
}
