#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Left2,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int deadZone = 15;

task main()
{
	waitForStart();
	while(true)
	{
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_y1) > deadZone)
		{
			motor[Left] = -joystick.joy1_y1;
			motor[Left2] = joystick.joy1_y1;
		}
		else
		{
			motor[Left] = 0;
			motor[Left2] = 0;
		}

		if(abs(joystick.joy1_y2) > deadZone)
		{
			motor[Right] = -joystick.joy1_y2;
			motor[Right2] = -joystick.joy1_y2;
		}
		else
		{
			motor[Right] = 0;
			motor[Right2] = 0;
		}
	}
}
