#pragma config(Motor,  motorA,          Lift,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int MotorSpeed;
	while(true)
	{
  	if(nNxtButtonPressed == 1)
  	{
   		MotorSpeed = 50;
  	}
  	if(nNxtButtonPressed == 2)
		{
			MotorSpeed += 5;
		}
		motor[Lift] = MotorSpeed;
	}
}
