#pragma config(Motor,  motorA,          Lift,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	const int defaultSpeed = 50;
	int motorSpeed = defaultSpeed;
	const int speedDifference = 10;
	while(true)
	{
		//Right arrow to speed up
  	if(nNxtButtonPressed == 1)
  	{
  		while(nNxtButtonPressed == 1)
  		{

  		}
   		motorSpeed += speedDifference;
  	}
  	//Left arrow to slow down
  	if(nNxtButtonPressed == 2)
		{
			while(nNxtButtonPressed == 2)
			{

			}
			motorSpeed -= speedDifference;
		}
		//Center button to return to normal speed
		if(nNxtButtonPressed == 3)
		{
			while(nNxtButtonPressed == 3)
			{

			}
			motorSpeed = defaultSpeed;
		}
		motor[Lift] = motorSpeed;
	}
}
