#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorC,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     ForkLift,      tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main ()
{
	waitForStart();
	ClearTimer(T1);

	//Move forward away from the square E, 1 and stop at square C, 1
	while(time1[T1] < 2000)
	{
		motor[Right] = 60;
		motor[Left] = -60;
	}
	//Turn right
	ClearTimer(T1);

	while(time1[T1] < 1600)
	{
		motor[Right] = -60;
		motor[Left] = -60;
	}
	//and move forward 1 sqaure
	ClearTimer(T1);

	while(time1[T1] < 1000)
	{
		motor[Right] =  60;
		motor[Left] = -60;
	}
}
