#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S3,     Seeker,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C2_1,     Left,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     ForkLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "C:\Users\Public\Ftc\drivers\2.3\drivers\HTIRS2-driver.h"
#include "JoystickDriver.c"

int motorPower = 50;
int locBeacon;

task main ()
{
	//int lastValue = 0;
  waitForStart();

  //drive away from the wall
  nMotorEncoder[Left]=0;
  nMotorEncoder[Right]=0;
  wait1Msec(100);

  while (nMotorEncoder[Right] > -2700)
  {
  	motor[Left] = motorPower;
  	motor[Right] = motorPower;
  }

	motor[Left]=0;  //stop
	motor[Right]=0;
  wait1Msec(1000);

  //where is the beacon?
	locBeacon = SensorValue[Seeker];
	wait1Msec(50);
	//backup a bit
	nMotorEncoder[Left] = 0;
	nMotorEncoder[Right] = 0;
	wait1Msec(100);

	while(nMotorEncoder[Right] < 180)
	{
		motor[Left] = -motorPower;
		motor[Right] = -motorPower;
	}

	//turn left or right
  nMotorEncoder[Left]=0;
  nMotorEncoder[Right]=0;
  wait1Msec(100);

  if(locBeacon > 5) //turn to right post
  {
	  while (nMotorEncoder[Right] > -1440)
	  {
	  	motor[Left] = motorPower;
	  	motor[Right] = -motorPower;
	  }
  }
  else if(locBeacon < 5)  //turn to left post
  {
	  while (nMotorEncoder[Right] < 1440)
	  {
	  	motor[Left] = -motorPower;
	  	motor[Right] = motorPower;
	  }
  }
  else
  {
  	wait1Msec(10000);  //this is waste!!  take it out.
	}

  // go forward to the correct post (this needs to be a bit less)
  nMotorEncoder[Left]=0;
  nMotorEncoder[Right]=0;
  wait1Msec(100);

  while(nMotorEncoder[Left] > -2160)
  {
  	motor[Left] = motorPower;
  	motor[Right] = motorPower;
  }

  // IR Seeker
  while(1 == 1)
	{
		if(SensorValue[Seeker] == 5)	//If the sensor is lined up with the beacon...
		{
			//...drive straight.
			//lastValue = SensorValue[Seeker];
			motor[Left] = motorPower/2;
			motor[Right] = motorPower/2;
		}
		else if(SensorValue[Seeker] == 0)	//If the sensor is lined up with the beacon...
		{
			//...do nothing
			// spurrious "0"
			motor[Left] = 0;
			motor[Right] = 0;
		}
		else if(SensorValue[Seeker] > 5)	//If the right side of the sensor detects the beacon...
		{
			//...turn right.
			//lastValue = SensorValue[Seeker];
			motor[Left] = motorPower;
			motor[Right] = -motorPower;
		}
		else if(SensorValue[Seeker] < 5)	//If the left side of the sensor detects the beacon (or doesn't see it)...
		{
			//...turn left.
			//lastValue = SensorValue[Seeker];
			motor[Left] = -motorPower;
			motor[Right] = motorPower;
		}
		else{
			// do nothing
		}
	}
}
