#pragma config(Hubs,	S1, HTServo,	HTMotor,	none,			none)
#pragma config(Sensor, S1,		 ,							 sensorI2CMuxController)
#pragma config(Motor,	 mtr_S1_C2_1,			Left,					 tmotorNormal, openLoop, reversed)
#pragma config(Motor,	 mtr_S1_C2_2,			Right,				 tmotorNormal, openLoop)
#pragma config(Servo,	 srvo_S1_C1_1,		servo1,								tServoNone)
#pragma config(Servo,	 srvo_S1_C1_2,		servo2,								tServoNone)
#pragma config(Servo,	 srvo_S1_C1_3,		servo3,								tServoNone)
#pragma config(Servo,	 srvo_S1_C1_4,		servo4,								tServoNone)
#pragma config(Servo,	 srvo_S1_C1_5,		servo5,								tServoNone)
#pragma config(Servo,	 srvo_S1_C1_6,		servo6,								tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

//All comments to most of this code is in TeleOpJarrod.c
#include "JoystickDriver.c"
int deadZone = 15;

task main()
{
	waitForStart();
	while(true)
	{
		getJoystickSettings(joystick);
		if(joy1Btn(7) == 1)
		{
			if(abs(joystick.joy1_y1) > deadZone)
			{
  			motor[Left] = (joystick.joy1_y1) / 6;
			}
			if(abs(joystick.joy1_y2) > deadZone)
			{
				motor[Right] = (joystick.joy1_y2) / 6;
			}
		}
		else
		{
		  if(abs(joystick.joy1_y1) > deadZone)
		  {
			  motor[Left] = (joystick.joy1_y1);
		  }
		  else
		  {
			  motor[Left] = 0;
		  }

		  if(abs(joystick.joy1_y2) > deadZone)
		  {
		  	motor[Right] = (joystick.joy1_y2);
		  }
		  else
		  {
		  	motor[Right] = 0;
		  }
  	}
	}
}
