#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     press,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     turn,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//turn turntable
if(SensorValue[press] == 1)
{
	motor[turn] =50;
}
else
{
	motor[turn] =0;
}

//when pressed turn
//when not pressed don't turn


}
