#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     gyroSensor,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IRSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     mtrFR,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mtrBR,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     mtrFL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     mtrBL,         tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    goalGrabber,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    irRotator,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TANK_4M

#include "includes.h"

task main()
{
	InitializeAuto();
	waitForStart();

	//Robot goes partally to the goal
	//Robot turns to line up with goal
	//Robot drives backward until it reaches the rolling goal
	//Goal grabbers extend
	//Robot drives back towards ramp
	//Robot turns right to go to parking zone
	//Robot drives strait toward parking zone
	//Robot turns while in parking zone
	//Robot ensures goal is in parking zone
	//Robot turns more to get into the parking zone better
	//Robot backs up to ensure goal is in parking zone

	DriveBackwardDistance(60, 20);
	TurnLeftDegrees(7, 50);
	DriveBackwardDistance(27, 20);
	GrabGoal();
	DriveBackwardDistance(8, 20);
	wait1Msec(500);
	TurnRightDegrees(19, 50);
	wait1Msec(100);
	DriveForwardDistance(93, 60);
	TurnRightDegrees(130, 50);
	DriveBackwardDistance(20, 20);
	ReleaseGoal();
	DriveForwardDistance(70, 60);
	TurnRightDegrees(115, 50);
	DriveBackwardDistance(53, 20);
	wait1Msec(200);
	GrabGoal();
	//DriveBackwardDistance(8, 20);
	wait1Msec(500);
	DriveForwardDistance(48, 20);
	TurnRightDegrees(10, 50);
	DriveForwardDistance(45, 60);
	TurnLeftDegrees(135, 50);
	DriveBackwardDistance(17, 20);
}
