#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     mtrL,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mtrR,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    goalGrabber,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Library/motors/autoDriveFunctions.c"

task main()
{
	//#inlcude "initialize robot"
	//waitForStart
	//Robot drives backward until it reaches the rolling goal
	while(nMotorEncoder[mtrL] > 21600)
	{
		DriveStrait(-100);
	}
	DriveStrait(0);

	//Goal grabbers extend
	servo[goalGrabber] = 128;

	//Robot drives back towards ramp
	while(nMotorEncoder[mtrL] < 15000)
	{
		DriveStrait(100);
	}
	DriveStrait(0);

	//Robot turns right to go to parking zone
	while(nMotorEncoder[mtrR] <  2800)
	{
		TurnRight(50);
	}
	DriveStrait(0);

	//Robot drives strait toward parking zone
	while(nMotorEncoder[mtrL] < 1000)
	{
		DriveStrait(100);
	}
	DriveStrait(0);
}
