#include "../Library/drive_modes/tank_4m.c"
#include "../Library/autonomous/auto_drive.c"
#include "../Library/sensors/ir_seeker.c"
#include "center_objectives.c"
#include "JoystickDriver.c"
#include "init_auto.c"
