#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     mtrL,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mtrR,          tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Library/motors/motors.c"
#include "../Library/controllers/tank.c"

task main()
{
	StartTask(Controller);
	StartTask(Drive);
	while(true)
	{
		//Main loop
	}
}
