#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     mtrL,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     mtrR,          tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);

		motor[mtrL] = 50;
		motor[mtrR] = 50;

	}
}
