#pragma config(Motor,  motorA,          left,          tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
#pragma debuggerWindows("joystickSimple");

#include "motors.c"
#include "JoystickDriver.c"
