#pragma config(Motor,  motorA,          single,        tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
//#pragma debuggerWindows("joystickSimple");

#include "motors.c"
#include "JoystickDriver.c"



task main()
{
	while(true)
	{
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_y1) > 15)
		{
			DriveMotor(joystick.joy1_y1);
		}
		else
		{
			DriveMotor(0);
		}
	}
}
