#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     TopR,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     TopL,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BottR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BottL,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int deadZone = 10;

task main()
{
	waitForStart();
	while(true)
	{
		if(joy1Btn(7) == 1)
		{
			if(abs(joystick.joy1_y1) > deadZone && abs(joystick.joy1_x1) > deadZone)
			{
				if(joystick.joy1_y1/joystick.joy1_x1 > 0)
				{
					motor[TopL] = joystick.joy1_y1/5;
					motor[BottR] = -joystick.joy1_y1/5;
				}
				else if(joystick.joy1_y1/joystick.joy1_x1 < 0)
				{
					motor[TopR] = -joystick.joy1_y1/5;
					motor[BottL] = joystick.joy1_y1/5;
				}
			}
			else if(abs(joystick.joy1_y1) > deadZone)
			{
				motor[TopR] = -joystick.joy1_y1/5;
				motor[BottR] = -joystick.joy1_y1/5;
				motor[TopL] = joystick.joy1_y1/5;
				motor[BottL] = joystick.joy1_y1/5;
			}
			else if(abs(joystick.joy1_x1) > deadZone)
			{
				motor[TopR] = joystick.joy1_x1/5;
				motor[BottR] = -joystick.joy1_x1/5;
				motor[TopL] = joystick.joy1_x1/5;
				motor[BottL] = -joystick.joy1_x1/5;
			}
			else if(abs(joystick.joy1_y2) > deadZone)
			{
				motor[TopR] = joystick.joy1_y2/5;
				motor[BottR] = joystick.joy1_y2/5;
				motor[TopL] = joystick.joy1_y2/5;
				motor[BottL] = joystick.joy1_y2/5;
			}
			else
			{
				motor[TopR] = 0;
				motor[BottR] = 0;
				motor[TopL] = 0;
				motor[BottL] = 0;
			}

		}
		else
		{
			if(abs(joystick.joy1_y1) > deadZone && abs(joystick.joy1_x1) > deadZone)
			{
				if(joystick.joy1_y1/joystick.joy1_x1 > 0)
				{
					motor[TopL] = joystick.joy1_y1;
					motor[BottR] = -joystick.joy1_y1;
				}
				else if(joystick.joy1_y1/joystick.joy1_x1 < 0)
				{
					motor[TopR] = -joystick.joy1_y1;
					motor[BottL] = joystick.joy1_y1;
				}
			}
			else if(abs(joystick.joy1_y1) > deadZone)
			{
				motor[TopR] = -joystick.joy1_y1;
				motor[BottR] = -joystick.joy1_y1;
				motor[TopL] = joystick.joy1_y1;
				motor[BottL] = joystick.joy1_y1;
			}
			else if(abs(joystick.joy1_x1) > deadZone)
			{
				motor[TopR] = joystick.joy1_x1;
				motor[BottR] = -joystick.joy1_x1;
				motor[TopL] = joystick.joy1_x1;
				motor[BottL] = -joystick.joy1_x1;
			}
			else if(abs(joystick.joy1_y2) > deadZone)
			{
				motor[TopR] = joystick.joy1_y2;
				motor[BottR] = joystick.joy1_y2;
				motor[TopL] = joystick.joy1_y2;
				motor[BottL] = joystick.joy1_y2;
			}
			else
			{
				motor[TopR] = 0;
				motor[BottR] = 0;
				motor[TopL] = 0;
				motor[BottL] = 0;
			}
		}

	}
}
