#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     Front,          sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     TopR,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     TopL,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BottR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BottL,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int motorPower = 100;

task main()
{
	waitForStart();
	while(true)
	{
		if(SensorValue[Front] == 5)
		{
			while(SensorValue[Front] == 5)
			{
				motor[TopR] = -motorPower;
				motor[BottR] = -motorPower;
				motor[TopL] = motorPower;
				motor[BottL] = motorPower;
			}
		}
		else
		{
			motor[TopR] = 0;
			motor[BottR] = 0;
			motor[TopL] = 0;
			motor[BottL] = 0;
		}

		if(SensorValue[Front] > 5)
		{
			while(SensorValue[Front] > 5)
			{
				motor[TopR] = -motorPower;
				motor[BottR] = -motorPower;
				motor[TopL] = -motorPower;
				motor[BottL] = -motorPower;
			}
		}
		else
		{
			motor[TopR] = 0;
			motor[BottR] = 0;
			motor[TopL] = 0;
			motor[BottL] = 0;
		}

		if(SensorValue[Front] < 5)
		{
			while(SensorValue[Front] < 5)
			{
				motor[TopR] = motorPower;
				motor[BottR] = motorPower;
				motor[TopL] = motorPower;
				motor[BottL] = motorPower;
			}
		}
		else
		{
			motor[TopR] = 0;
			motor[BottR] = 0;
			motor[TopL] = 0;
			motor[BottL] = 0;
		}
	}
}
