#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    servoFR,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    servoFL,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    servoBL,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    servoBR,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_5,    servoBrush1,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_6,    servoBrush2,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifndef SWIVE_DRIVE_FUNCTIONS.C
#define SWIVE_DRIVE_FUNCTIONS.C

#include "Joystick_Swive_Functions.c"

#define TICK_TO_DEGREE_MOTOR (0.46)
#define DEGREE_TO_TICK_SERVO (0.71)
#define SWIVE_GEAR_RATIO_MOTOR (1.3)
#define SWIVE_GEAR_RATIO_SERVO (0.5)

task main
{

}

void DriveSwive(string loc, int dir, int power)
{
	DriveSwiveMotor(loc, power);
	SetSwiveServo(loc, dir);
}

void DriveSwiveMotor(string loc, int power)
{
	if (loc == "FR")
	{
		motor[motorFR] = power;
	}
	else if (loc == "FL")
	{
		motor[motorFL] = power;
	}
	else if (loc == "BL")
	{
		motor[motorBL] = power;
	}
	else
	{
		motor[motorBR] = power;
	}
}

void SetSwiveServo(string loc, int dir)
{
	if (loc == "FR")
	{
		servo[servoFR] = dir * DEGREE_TO_TICK_SERVO;
	}
	else if (loc == "FL")
	{
		servo[servoFL] = dir * DEGREE_TO_TICK_SERVO;
	}
	else if (loc == "BL")
	{
		servo[servoBL] = dir * DEGREE_TO_TICK_SERVO;
	}
	else
	{
		servo[servoBR] = dir * DEGREE_TO_TICK_SERVO;
	}
}
void TomDriveSwive()
{
	DriveSwive(FR, tomDir, TomSpeed(FR) * GetJoystickPower);
	DriveSwive(FL, tomDir, TomSpeed(FL) * GetJoystickPower);
	DriveSwive(BL, tomDir, TomSpeed(BL) * GetJoystickPower);
	DriveSwive(BR, tomDir, TomSpeed(BR) * GetJoystickPower);
}

#endif
