#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S2_C1_1,    testServo,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


bool whileRecording = true;
int gyroValue;

task MoveServo()
{
	servo[testServo] = 0;
	while (whileRecording == true)
	{
		servo[testServo] = 150;
		wait1Msec(100);

		if (ServoValue[testServo] <= 150 && time1[T1] != NULL)
		{
			gyroValue = SensorValue(gyro) - 593;
		}
	}

}

task main()
{
	time1[T1] = 0;
	servo[testServo] = 0;
	servo[testServo] = 150;
	wait1Msec(100);

	if (gyroValue >= 211)
	{
		time1[T1]
	}
	int gyroValue = SensorValue(gyro) - 593;
	int time = time1[T1];
	StartTask(MoveServo);
}
