#pragma config(Sensor, S2,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "ir_seeker.c"
#include "../../Library/drive_modes/tank_2m.c"
#pragma debuggerWindows("nxtLCDScreen");
#pragma debuggerWindows("nxtDevices");
const int QUARTER_IMPULSE = 25;
const int MIDDLE_IR = 5;
task main()
{
	RegisterIRSeeker(ir);
	RegisterDriveMotors(leftMotor, rightMotor);
	int irVal = ReadIR();
	ASSUME_CONTROLLER_INPUT = false;

	while(true)
	{

		getJoystickSettings(joystick);
		irVal = ReadIR();
		if(irVal < MIDDLE_IR)
		{
			TurnRight(QUARTER_IMPULSE);
		}
		else if (irVal > MIDDLE_IR)
		{
			TurnLeft(QUARTER_IMPULSE);
		}
		else
		{
			DriveForward(-1 * QUARTER_IMPULSE);
		}


		//read ir sensor
			//local value
			//update value each time
		//turn right if value is > 5
		//turn left if value is < 5
		//drive forward if value = 5
		//turn left or right depending on reading
			//
	  //turn until reading is 5
		//drive forward




	}
}
