#pragma config(Motor,  motorA,          single,        tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
//#pragma debuggerWindows("joystickSimple");

#include "motors.c"
#include "JoystickDriver.c"

int returnvalue = 50;

task main()
{
	RunMotorForOneSecond(100);
	while(true)
	{
		getJoystickSettings(joystick);


	}
}
