#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Left2,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Code Review by Darrell
 - Magic numbers break style guide
 - motors should be using library. bare minimum they should be using functions
 - encoder access should be using library
 - file lacks comments and name of file does not adequately describe what it is for
*/

#include "JoystickDriver.c"

task main()
{
	waitForStart();

	while(nMotorEncoder[Right] < 2880)
	{
		motor[Right] = 50;
		motor[Right2] = 50;
		motor[Left] = -50;
		motor[Left2] = -50;
	}
	motor[Right] = 0;
	motor[Right2] = 0;
	motor[Left] = 0;
	motor[Left2] = 0;
	}
