#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IROne,          sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     IRTwo,          sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Left2,         tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Joystickdriver.c"

int motorPower = 60;

//this is for the first position of the center goal
void BeaconPos1()
{
	//move the robot forward 3-4 rotations
		while(nMotorEncoder[Left] <= 4320)
		{
			motor[Right] = motorPower;
			motor[Right2] = 60;
			motor[Left] = motorPower;
			motor[Left2] = motorPower;
		}
		motor[Right] = 0;
		motor[Right2] = 0;
		motor[Left] = 0;
		motor[Left2] = 0;
		nMotorEncoder[Left] = 0;

	//turn the robot by half a rotation
		while(nMotorEncoder[Left] >= -720)
		{
			motor[Right] = motorPower;
			motor[Right2] = motorPower;
			motor[Left] = -motorPower;
			motor[Left2] = -motorPower;
		}
		motor[Right] = 0;
		motor[Right2] = 0;
		motor[Left] = 0;
		motor[Left2] = 0;
		nMotorEncoder[Left] = 0;

	//move the robot forward by 2 rotations
		while(nMotorEncoder[Left] <= 2160)
		{
			motor[Right] = motorPower;
			motor[Right2] = motorPower;
			motor[Left] = motorPower;
			motor[Left2] = motorPower;
		}
		motor[Right] = 0;
		motor[Right2] = 0;
		motor[Left] = 0;
		motor[Left2] = 0;
		nMotorEncoder[Left] = 0;
}

void BeaconPos2()
{
	//move the robot forward by 3.5-4.5 rotations
	while(nMotorEncoder[Left] <= 4420)
	{
		motor[Left] = motorPower;
		motor[Left2] = motorPower;
		motor[Right] = motorPower;
		motor[Right2] = motorPower;
	}
	motor[Left] = 0;
	motor[Left2] = 0;
	motor[Right] = 0;
	motor[Right2] = 0;
	nMotorEncoder[Left] = 0;

	//turn the robot by about half a rotation
	while(nMotorEncoder[Left] >= -720)
	{
		motor[Left] = -motorPower;
		motor[Left2] = -motorPower;
		motor[Right] = motorPower;
		motor[Right2] = motorPower;
	}
	motor[Left] = 0;
	motor[Left2] = 0;
	motor[Right] = 0;
	motor[Right2] = 0;
	nMotorEncoder[Left] = 0;

	//move forward by two rotations
	while(nMotorEncoder[Left] <= 2160)
	{
		motor[Left] = motorPower;
		motor[Left2] = motorPower;
		motor[Right] = motorPower;
		motor[Right2] = motorPower;
	}
	motor[Left] = 0;
	motor[Left2] = 0;
	motor[Right] = 0;
	motor[Right2] = 0;
	nMotorEncoder[Left] = 0;
}

void BeaconPos3()
{
	while(nMotorEncoder[Left] <= 4520)
	{
		motor[Left] = motorPower;
		motor[Left2] = motorPower;
		motor[Right] = motorPower;
		motor[Right2] = motorPower;
	}
	motor[Left] = 0;
	motor[Left2] = 0;
	motor[Right] = 0;
	motor[Right2] = 0;
	nMotorEncoder[Left] = 0;

	while(nMotorEncoder[Left] >= -720)
	{
		motor[Left] = motorPower;
		motor[Left2] = motorPower;
		motor[Right] = motorPower;
		motor[Right2] = motorPower;
	}
	motor[Left] = 0;
	motor[Left2] = 0;
	motor[Right] = 0;
	motor[Right2] = 0;
	nMotorEncoder[Left] = 0;

	while(nMotorEncoder[Left] <= 2160)
	{
		motor[Left] = motorPower;
		motor[Left2] = motorPower;
		motor[Right] = motorPower;
		motor[Right2] = motorPower;
	}
	motor[Left] = 0;
	motor[Left2] = 0;
	motor[Right] = 0;
	motor[Right2] = 0;
	nMotorEncoder[Left] = 0;
}

task main()
{
	waitForStart();
	nMotorEncoder[Right] = 0;
	nMotorEncoder[Left] = 0;

	while(true)
	{
			if(SensorValue[IROne] == 4 && SensorValue[IRTwo] == 6)
			{
				BeaconPos1();
			}
			else if(SensorValue[IROne] == 5 && SensorValue[IRTwo] == 7)
			{
				BeaconPos2();
			}
			else if(SensorValue[IROne] == 6 && SensorValue[IRTwo] == 5)
			{
				BeaconPos3();
			}
	}
}
