#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Left2,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	waitForStart();
	ClearTimer(T1);

	while(time1[T1] < 1500)
	{
		motor[Right] = 50;
		motor[Right2] = 50;
		motor[Left] = -50;
		motor[Left2] = -50;
	}
	motor[Right] = 0;
	motor[Right2] = 0;
	motor[Left] = 0;
	motor[Left2] = 0;
	ClearTimer(T1);




}
