#pragma config(Motor,  motorA,          single,        tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("nxtLCDScreen");
//#pragma debuggerWindows("Servos");
//#pragma debuggerWindows("joystickSimple");

#include "controller.c"
#include "PID.c"

task main()
{
	StartTask(PID);
	StartTask(controller);
	while(true)
	{
	}
}
