#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if (nNxtButtonPressed == 0)
		{
			motor[motor1] = 50;
		}
		else if (nNxtButtonPressed == 3)
		{
			motor[motor2] = 50;
		}
		else
		{
			motor[motor1] = 0;
			motor[motor2] = 0;
		}
		wait10Msec(50);
	}


}
